---
name: strategy-optimizer_env_bck
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - nbformat
  - numpy
  - pandas-ta
  - pip
  - python=3.12
  - sqlite=3.50.2
  - ta-lib
  - pip:
      - backtesting
      - tulipy
